
RUN git clone https://github.com/opencv/opencv.git
ENV CUDA_HOME=/usr/local/cuda
ENV LD_LIBRARY_PATH=$CUDA_HOEM/lib64:$LD_LIBRARY_PATH
RUN apt-get -y install cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
RUN apt-get install -y python-dev python-numpy
RUN apt-get install -y libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev
RUN apt-get install -y libblas-dev liblapack-dev
RUN cd opencv && mkdir build && cd build && cmake -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D CUDA_CUDA_LIBRARY=/usr/local/cuda/targets/x86_64-linux/lib/stubs/libcuda.so \
  -D WITH_CUDA=ON \
  -D ENABLE_FAST_MATH=1 \
  -D CUDA_FAST_MATH=1 \
  -D WITH_CUBLAS=1 \
  -D INSTALL_PYTHON_EXAMPLES=ON \
  -D WITH_TBB=ON \
  -D BUILD_NEW_PYTHON_SUPPORT=ON \
  -D WITH_V4L=ON \
  -D INSTALL_C_EXAMPLES=ON \
  -D BUILD_EXAMPLES=ON \
  -D WITH_QT=ON \
  -D WITH_GTK=ON \
  -D WITH_OPENGL=ON ..
RUN cd /root/opencv/build && make && sudo make install

RUN luarocks install https://raw.githubusercontent.com/bshillingford/nnquery/master/rocks/nnquery-scm-1.rockspec
RUN luarocks install https://raw.githubusercontent.com/deepmind/torch-hdf5/master/hdf5-0-0.rockspec
RUN luarocks install cv

# RUN luarocks install thrift
# RUN luarocks install dataset
# RUN luarocks install luaposix
# RUN luarocks install moses
# RUN luarocks install luasocket
# RUN luarocks install parallel
# RUN luarocks install ipc
# RUN luarocks install distlearn
# RUN luarocks install autograd
# RUN luarocks install dpnn
